steps:
  detectExecuteScan:
    projectName: 'SHC - CLOUD SDK'
    groups:
      - 'CLOUD SDK 4.0'
    serverUrl: 'https://sap.blackducksoftware.com/'
    mavenExcludedScopes: ["provided", "test"]
    failOn: ['BLOCKER', 'CRITICAL', 'MAJOR']
    versioningModel: "major"

stages:
  test:
    coverageThresholds:
      instruction: 79
      branch: 72
      complexity: 70
      line: 80
      method: 77
      class: 85
  codeCheck:
    checkstyle:
      high: '14'# Open tasks (to do or fix me)
      normal: '0'
      low: '216'
    findbugs: #SpotBugs
      high: '0'
      normal: '0'
      low: '0'
    pmd:
      high: '0'
      normal: '19'
      low: '10'
