steps:
  detectExecuteScan:
    projectName: 'SHC - CLOUD SDK'
    groups:
      - 'CLOUD SDK 4.0'
    serverUrl: 'https://sap.blackducksoftware.com/'
    mavenExcludedScopes: ["provided", "test"]
    failOn: ['BLOCKER', 'CRITICAL', 'MAJOR']
    versioningModel: "major"

stages:
  test:
    coverageThresholds:
      instruction: 75
      branch: 68
      complexity: 66
      line: 76
      method: 73
      class: 82
  codeCheck:
    checkstyle:
      high: '14'
      normal: '-1'
      low: '-1'
    findbugs:
      high: '10'
      normal: '-1'
      low: '-1'
    pmd:
      high: '0'
      normal: '19'
      low: '10'
